let languagesObject = {
  en: {
    login: {
      appTitle: "Simple - CRM",
      appComment: "Lorem, ipsum dolor sit amet consectetur adipisicing elit.",
      pageTitle: "Sign in",
      signIn: "Sign in",
      help: "Help",
      privacy: "Privacy",
      term: "Terms",
      comment: "Enter username and password to log in",
      rights: "All Rights Reserved"
    },
    auth: {
      userLabel: "User",
      userFeed: "Please enter your user name.",
      passwordLabel: "Password",
      passwordFeed: "Please enter your password.",
      passwordRemember: "Remember me",
      logIn: "Log in",
      logInFail: "User or Password wrong", 
    },
    breadcrumb: {
      Home: "Home",
      Users: "Users",
      List: "List",
      Partner: "Partner",
      Contracts: "Contracts",
      Invoices: "Invoices",
      Offers: 'Offers',
      Inventory: "Inventory",
      Products: "Products",
      Profile: "Profile"
    },
    header: {
      title: "Simple - CRM",
      logOutTitle: "Log Out",
      logOutText: "Are you sure you want to log out?",
      confirmButtonText: "Yes",
      cancelButtonText: "No",
      profile: "Profile",
      logOut: "Log out"
    },
    home: {
      title: "Home",
      sales: "Sales",
      salesMoment: "Today",
      salesStatus: "Increases",
      revenue: "Ingresos",
      revenueMoment: "Today",
      revenueStatus: "Increases",
      partner: "Clientes",
      partnerMoment: "Today",
      partnerStatus: "Decreases"
    },
    menucard: {
      title: "Filter",
      Today: "Today",
      thisMonth: "This Month",
      thisYear: "This Year"
    },
    datatable: {
      actions: "Actions",
      edit: "Edit",
      delete: "Delete",
      empty: "There are no data to show"
    },
    users: {
      title: "Users",
      waitMsg: "Please, wait",
      addTitle: "Add Users",
      addSuccess: "The user has been created successfully",
      addError: "An error occurred while querying the API",
      editTitle: "Modify User",
      editSuccess: "The user has been successfully modified",
      editError: "An error occurred while querying the API",
      delTitle: "Delete User",
      delSuccess: "ser deleted successfully",
      delError: "An error occurred while querying the API",
      delMessage: "You're sure ?",
      delWarning: "This option cannot be reversed !",
      user: "User",
      name: "Name",
      dni: "DNI",
      job: "Job",
      email: "Email",
      phone: "Phone",
      tableTitle: "List of",
      filterOn: "Filter",
      filterOff: "Remove Filter",
      btnNew: "New",
    },
    userform: {
      newTitle: "New User",
      editTitle: "Edit User",
      userName: "Username",
      userNameFeed: "Please type the username.",
      dni: "DNI",
      dniFeed: "please type the DNI.",
      fullName: "Full name",
      fullNameFeed: "Please enter the User's Full Name.",
      job: "Job",
      email: "Email",
      emailFeed: "Please enter the user's email.",
      capsLock: "Disable Caps Lock",
      phone: "Phone",
      password: "Password",
      passwordFeed: "Please type a valid password.",
      btnClose: "Close",
      btnSubmit: "Save"
    },
    filterform: {
      title: "Filter",
      criteriaKey: "Filter by",
      select: "Selections...",
      userName: "User Name",
      fullName: "Full Name",
      dni: "DNI",
      criterialKeyFeed: "Please enter select the criteria for the filter.",
      criteriaValue: "Value",
      criteriaValueFeed: "Please type the value of the criteria for the filter.",
      btnClose: "Close",
      btnAccept: "Accept"
    },
    services: {
      badRoute: "The method is not available in this route",
      badScheema: "Wrong Authentication Scheme"
    }
  },
  es: {
    login: {
      appTitle: "Simple - CRM",
      appComment: "Lorem, ipsum dolor sit amet consectetur adipisicing elit.",
      pageTitle: "Autentificar",
      signIn: "Autentificar",
      help: "Ayuda",
      privacy: "Privacidad",
      term: "Codiciones",
      comment: "Entre nombre de usuario y contraseña para autentificarse",
      rights: "Todos los derechos reservados"
  
    },
    auth: {
      userLabel: "Usuario",
      userFeed: "Por favor entre su nombre de usuario.",
      passwordLabel: "Contraseña",
      passwordFeed: "Por favor entre su contraseña.",
      logIn: "Log in",
      logInFail: "User or Password wrong", 
      logIn: "Iniciar sesión",
      logInFail: "Usuario o contraseña incorrecta", 
    },
    breadcrumb: {
      Home: "Inicio",
      Users: "Usuarios",
      List: "Listado",
      Partner: "Clientes",
      Contracts: "Contratos",
      Offers: "Ofertas",
      Invoices: "Facturas",
      Inventory: "Inventario",
      Products: "Productos",
      Profile: "Perfil"
    },
    header: {
      title: "Simple - CRM",
      logOutTitle: "Cerrar Sesión",
      logOutText: "Esta seguro que desea cerrar la sesión ?",
      confirmButtonText: "Sí",
      cancelButtonText: "No",
      profile: "Perfil",
      logOut: "Desconectarse"
    },
    home: {
      title: "Inicio",
      sales: "Ventas",
      salesMoment: "Hoy",
      salesStatus: "Aumenta",
      revenue: "Ingresos",
      revenueMoment: "Hoy",
      revenueStatus: "Aumenta",
      partner: "Clientes",
      partnerMoment: "Hoy",
      partnerStatus: "Disminuye"
    },
    menucard: {
      title: "Filtrar",
      Today: "Hoy",
      thisMonth: "Este Mes",
      thisYear: "Este Año"
    },
    datatable: {
      actions: "Acciones",
      edit: "Editar",
      delete: "Eliminar",
      empty: "No existen datos para Mostrar"
    },
    users: {
      title: "Usuarios",
      waitMsg: "Por favor, espere",
      addTitle: "Adicionar Usuarios",
      addSuccess: "El usuario se ha creado con éxito",
      addError: "Ha ocurrido un error al consultar la API",
      editTitle: "Modificar Usuario",
      editSuccess: "El usuario se ha modificado con éxito",
      editError: "Ha ocurrido un error al consultar la API",
      delTitle: "Eliminar Usuario",
      delSuccess: "Usuario eliminado con éxito",
      delError: "Ha ocurrido un error al consultar la API",
      delMessage: "¿ Estás seguro ?",
      delWarning: "! Esta opción no podrá ser revertida !",
      user: "Usuario",
      name: "Nombre",
      dni: "DNI",
      job: "Cargo",
      email: "Correo",
      phone: "Teléfono",
      tableTitle: "Listado de",
      filterOn: "Filtrar",
      filterOff: "Quitar Filtro",
      btnNew: "Nuevo",
    },
    userform: {
      newTitle: "Nuevo Usuario",
      editTitle: "Editar Usuario",
      userName: "Nombre de Usuario",
      userNameFeed: "Por favor teclee el nombre de usuario.",
      dni: "DNI",
      dniFeed: "Por favor entre el DNI del usuario.",
      fullName: "Nombre y Apellidos",
      fullNameFeed: "Por favor entre el Nombre y los Apellidos del usuario.",
      job: "Cargo",
      email: "Correo",
      emailFeed: "Por favor entre el correo del usuario.",
      capsLock: "Desactive el Bloque de Mayúsculas",
      phone: "Teléfono",
      password: "Contraseña",
      passwordFeed: "Por favor teclee una contraseña valida.",
      btnClose: "Cerrar",
      btnSubmit: "Grabar"
    },
    filterform: {
      title: "Filtrar",
      criteriaKey: "Filtrar por",
      select: "Seleccione...",
      userName: "Nombre de Usuario",
      fullName: "Nombre Completo",
      dni: "DNI",
      criterialKeyFeed: "Por favor entre seleccione el críterio para el filtro.",
      criteriaValue: "Valor",
      criteriaValueFeed: "Por favor teclee el valor del críterio para el filtro.",
      btnClose: "Cerrar",
      btnAccept: "Aceptar"
    },
    services: {
      badRoute: "El método no esta disponible en esta ruta",
      badScheema: "Esquema de Autentificación erróneo"
    }    
  },
};

export default languagesObject;
